### ISSUE TITLE
Feature request: Allow volume to be passed with data to be imported

### ISSUE THREAD

**Issue by guneemwelloeux** [AndreySenov/firebase-tools-docker#46]
The Firebase emulators (Auth, Firestore and Storage in particular) allow data to be saved to a local folder upon exit, and imported at startup. This allows one to re-start the emulators with some data already populated.

It would be great for the Dockerfile to allow a volume to be attached, and read data from there, as is done in this other image, for example: https://github.com/SpineEventEngine/gcp-emulators/tree/master/firebase-emulator#provide-emulators-baseline-data

**Comment by ljacomin-fsl** [comment]
You can do it like this to start with data:

```yaml
services:
  emulators:
    image: andreysenov/firebase-tools
    volumes:
      - ./firebase.json:/home/node/firebase.json
      - ./data:/home/node/data
    command: /bin/bash -c "firebase emulators:start --import /home/node/data/firebase-emulator-data"
```
